# Generated by Django 3.1.1 on 2020-10-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created']},
        ),
    ]
